name: deploy in vercel

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  sync-db:
    runs-on: ubuntu-latest
    environment: MAIN
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: debugging env
      run: printenv
    - name: debugging database URL
      run: echo $DATABASE_URL
    - name: debugging database URL 2
      run: echo ${{ secrets.DATABASE_URL }}
    - name: Run migrations
      run: python manage.py migrate

  build:
    runs-on: ubuntu-latest
    environment: MAIN
    needs: sync-db
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - name: install vercel    
      run: npm i -g vercel
    - name: deploy to vercel
      run: npx vercel --prod -y --token=${{ secrets.VERCEL_TOKEN }}
